Make pre-commit hook faster
The four steps in the pre-commit hook leave the repository unchanged, so
they can be run in parallel without issue. The only problem is that the
output is no longer intelligible or deterministic, since it may be
interleaved. We work around this by assuming that the pre-commit hook
passes most of the time, and only showing detailed output when it fails,
by re-running the pre-commit hook serially.

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,6 +1,39 @@
 #!/bin/bash
 set -e
-poetry run py.test
-poetry run mypy bin pytch test
-poetry run black --check .
-poetry run flake8 bin pytch test
+
+run_in_serial() {
+    poetry run py.test
+    poetry run mypy bin pytch test
+    poetry run black --check .
+    poetry run flake8 bin pytch test
+}
+
+run_in_parallel() {
+    poetry run py.test &
+    readonly PYTEST_PID=$!
+    poetry run mypy bin pytch test &
+    readonly MYPY_PID=$!
+    poetry run black --check . &
+    readonly BLACK_PID=$!
+    poetry run flake8 bin pytch test &
+    readonly FLAKE8_PID=$!
+
+    wait $PYTEST_PID
+    wait $MYPY_PID
+    wait $BLACK_PID
+    wait $FLAKE8_PID
+}
+
+if [[ "$SERIAL" = 1 ]]; then
+    run_in_serial
+else
+    if ! run_in_parallel >/dev/null 2>&1; then
+        tput bold
+        tput setaf 1
+        echo "Error: pre-commit hook failed. Output below:"
+        tput sgr0
+        # Show more intelligible output, since running in parallel will
+        # interleave it.
+        run_in_serial
+    fi
+fi
